### ISSUE TITLE
Icon Document with Zero KB is created

### ISSUE THREAD

**Issue by electricarts** [lgarron/folderify#54] opened 2021-08-05 17:23 UTC
When I add an icon to the folder, an icon file with Zero KB is created inside the folder. When I delete this empty file, the folder icon also disappears and the normal folder icon is displayed again. Is this a "normal" behaviour?

<img width="886" alt="Screenshot 2021-08-05 at 19 13 47" src="https://user-images.githubusercontent.com/625286/128393851-66726b93-d6e8-4ce6-9f00-a1b567843453.png">

**Comment by lgarron** [comment] 2021-08-05 21:13
Yeah, this is how the resource fork for the icon shows up in macOS, and that's very much expected behaviour!

(At least for me. I have Finder set to show hidden files. Not sure under what conditions is shows up.)

Hope that helps. I'll close the issue since there's nothing actionable for us.

**Closed by lgarron** 2021-08-05 21:13 UTC
